### ISSUE TITLE
Automatically include fgprof in /debug/index

### ISSUE THREAD

**Issue by brancz** [felixge/fgprof#5] opened 2020-09-10 14:21 UTC
There is an [open issue](https://github.com/conprof/conprof/issues/69) on conprof (a continuous profiling project), discussing how there could be support for `fgprof`. It more generally started a discussion around custom/non-built-in profiles.

I haven't had a chance to dig into the `fgprof` code a lot yet, but looking at the bits and pieces involved, it appears that if profiles are created using the [pprof.NewProfile](https://golang.org/src/runtime/pprof/pprof.go?s=6806:6843#L198) function, then they are automatically included in profiles returned by [`pprof.Profiles()`](https://golang.org/src/runtime/pprof/pprof.go?s=7407:7433#L223), which is what the `/debug/pprof` index page [calls](https://golang.org/src/net/http/pprof/pprof.go?s=11657:11707#L353) to retrieve the list of available profiles.

I'll try to understand the code more and see if this is possible, but maybe you can tell directly off the top of your head, and whether if possible this is something you would accept a patch for? :) 

@felixge

**Comment by felixge** [comment] 2020-09-10 16:15
@brancz my understanding is that the current profile extension mechanism isn't suitable for fgprof.

The problem is that the only way to add a stack trace to a `*Profile` is the [Add()](https://golang.org/pkg/runtime/pprof/#Profile.Add) func which doesn't allow to providing the stack trace as a parameter. Instead the stack trace is captured inside of the `Add()` func based on the current stack. So there is no way to add the stacks of other goroutines to a `*Profile`, only the stack of the profiler goroutine could be added.

That being said, if you can think of a good way to inject the stack of other goroutines into `*Profile`, I'd be open to supporting this mechanism : ).

**Comment by brancz** [comment] 2020-09-10 16:21
I was afraid that is the case by reading over the code, but was hoping I was wrong :)

I'm gonna try and see if go might be interested in having a mechanism for this for profiles like fgprof. It doesn't seem totally wild considering that there is already the mechanism with `pprof.NewProfile()`.

**Comment by felixge** [comment] 2020-09-10 16:24
@brancz yeah, something like `func (p *Profile) AddStack(value interface{}, stack runtime.StackRecord)` might do the trick. But I'd have to prototype it a bit more to see if it would work with how the rest of the `*Profiler` extension mechanism works.

**Comment by felixge** [comment] 2022-08-27 12:45
Closing this since the upstream proposal was rejected.

**Closed by felixge** 2022-08-27 12:45 UTC
